/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package o;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.JTextComponent;

/**
 *
 * @author lily
 */
public class EasyCFrm extends javax.swing.JFrame {
    /**
     *
     */
    private static final long serialVersionUID = 1L;
    String stdin = "";
    int magic = 0;
    Translator t = new Translator();
    /**
     * Creates new form EasyCFrm
     */
    public EasyCFrm() {
        initComponents();
        this.setTitle("EasyC");
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize((int)(screenSize.getWidth()*0.8), (int)(screenSize.getHeight()*0.8));
        this.setIconImage(new ImageIcon("easyC.jpg").getImage());
        
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightMenu = new javax.swing.JPopupMenu();
        copy = new javax.swing.JMenu();
        paste = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        selectAll = new javax.swing.JMenu();
        save = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        run = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        outP = new javax.swing.JScrollPane();
        out = new javax.swing.JEditorPane();
        codeP = new javax.swing.JScrollPane();
        code = new javax.swing.JTextArea();
        rowP = new javax.swing.JScrollPane();
        row = new javax.swing.JTextArea();
        open = new javax.swing.JButton();
        input = new javax.swing.JButton();
        about = new javax.swing.JButton();

        rightMenu.setComponentPopupMenu(rightMenu);

        copy.setText("复制");
        copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                copyMouseClicked(evt);
            }
        });
        rightMenu.add(copy);

        paste.setText("粘贴");
        paste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pasteMouseClicked(evt);
            }
        });
        rightMenu.add(paste);
        rightMenu.add(jSeparator1);

        selectAll.setText("全选");
        rightMenu.add(selectAll);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        save.setText("另存为");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        exit.setText("退出");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        run.setText("编译并运行");
        run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runActionPerformed(evt);
            }
        });

        name.setFont(new java.awt.Font("黑体", 1, 36)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name.setText("EasyC 202003042154");
        name.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                nameMouseWheelMoved(evt);
            }
        });
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });

        out.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        out.setText("-- 输出 --");
        out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outMouseClicked(evt);
            }
        });
        outP.setViewportView(out);

        codeP.setFont(new java.awt.Font("宋体", 0, 32)); // NOI18N

        code.setColumns(1000);
        code.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        code.setLineWrap(true);
        code.setTabSize(4);
        code.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codeMouseClicked(evt);
            }
        });
        code.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                codeInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codeKeyTyped(evt);
            }
        });
        codeP.setViewportView(code);

        rowP.setRequestFocusEnabled(false);

        row.setEditable(false);
        row.setColumns(3);
        row.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        row.setLineWrap(true);
        row.setRows(5);
        row.setText("1");
        row.setToolTipText("");
        row.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rowP.setViewportView(row);

        open.setText("打开");
        open.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                openMouseWheelMoved(evt);
            }
        });
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });

        input.setText("输入");
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        about.setText("关于");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outP)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(open)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(run)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(about)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(name))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rowP, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codeP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(run, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(open, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(about, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeP)
                    .addComponent(rowP, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outP, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
	JFileChooser chooser = new JFileChooser();
	FileNameExtensionFilter filter = new FileNameExtensionFilter("C File(.c)", "c");
	chooser.setFileFilter(filter);
	int result = chooser.showSaveDialog(null);//frmnotePad是父窗体
	if (JFileChooser.APPROVE_OPTION == result) {
            try {
                String path = chooser.getSelectedFile().getPath();
                path = path.replaceAll(".c", "");
                EasyCUtilities.saveFile(chooser.getSelectedFile().getPath()+".c", code.getText());
//		System.out.println("你选择的文件名是："+chooser.getSelectedFile().getName());
//		System.out.println("文件的路径："+chooser.getCurrentDirectory());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(EasyCFrm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(EasyCFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runActionPerformed
        out.setText("");
        String compileText = "";
        String runText = "";
        
        if(code.getText().indexOf("scanf(") != -1 && (stdin == "" | stdin == null)){
            JOptionPane.showMessageDialog(null, "没有设置输入就运行，会导致软件假死。请设置输入。");
            return ;
        }
        
        
        try{
            EasyCUtilities.deleteExe();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "运行失败：删除旧可执行文件EasyC.exe失败！" );
        }
        
//        System.out.println("保存 C 源代码文件");
                
        try {
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");//设置日期格式
            out.setText(df.format(new Date()));
            EasyCUtilities.saveFile("EasyC.c", code.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "运行失败：保存 C 源代码文件失败！" );
        }
        
//        System.out.println("调用编译器");
        
        try{
            compileText = EasyCUtilities.compile();
            out.setText(out.getText() + compileText);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "运行失败：调用编译器失败！" );
        }
        
//        System.out.println("打开可执行文件");
        
        try{
            if(!compileText.contains("编译错误") && !out.getText().contains("fatal error:")){
//                out.setText(out.getText() + EasyCUtilities.run());
                runText = EasyCUtilities.run(stdin);
                out.setText(out.getText() + " \n" + runText);
                
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "运行失败：打开可执行文件失败！" );
        }
        
//        System.out.println("翻译");
        
        try{
            if(!compileText.equals("编译成功。\n")){
                out.setText("运行成功！"+t.translate(compileText)+runText+"\n输出原文："+compileText);
            }
        }catch(Exception e){
            out.setText(out.getText() + "Lily");
        }
        out.setCaretPosition(0);
    }//GEN-LAST:event_runActionPerformed

    private void outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outMouseClicked

        if(out.getText().equals("-- 控制台 --")){
            out.setText("");
        }
    }//GEN-LAST:event_outMouseClicked

    private void codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeKeyTyped

        int rowsNum = getRows()+1;
        StringBuffer sb = new StringBuffer("1");
        for(int i = 2; i <= rowsNum; i++){
            sb.append("\n"+i);
        }
        row.setText(sb.toString());
        //tab键加强
        
    }//GEN-LAST:event_codeKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        code.requestFocus();
        setLineAtCaret(getLineAtCaret(code));
        

      
    }//GEN-LAST:event_formWindowOpened

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed

        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked

        magic++;
        if(magic == 5){
            JOptionPane.showMessageDialog(null, "Bronya的嘴被胶带贴住了，不能说话。");
        }
        if(magic == 8){
            JOptionPane.showMessageDialog(null, "跟你说了多少次了，Bronya的嘴被胶带粘住了，不要再点了。");
        }
        if(magic >= 10){
                    code.setText("#include<stdio.h>\n" +
"int main(){\n" +
"	printf(\"Hello world! Hello EasyC! Hello Lily!\");\n" +
"}");
        }

    }//GEN-LAST:event_nameMouseClicked

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed

        JFileChooser chooser = new JFileChooser();
	FileNameExtensionFilter filter = new FileNameExtensionFilter("C File(.c)", "c");
	chooser.setFileFilter(filter);
	int result = chooser.showSaveDialog(null);//frmnotePad是父窗体
	if (JFileChooser.APPROVE_OPTION == result) {
            String path = chooser.getSelectedFile().getPath();
            try {
                code.setText(EasyCUtilities.open(path));
            } catch (IOException ex) {
                //do nothing..
            }
        }
    }//GEN-LAST:event_openActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        try{
            stdin = (String) JOptionPane.showInputDialog(null, "填写你的标准输入：(如需换行，请用\"<enter>\"来代替！）", "输入", 3, null, null, stdin);
        }catch(Exception e){
            //do nothing...
        }
        if(!"".equals(stdin) && stdin != null){
            input.setText("输入<已设置>");
        }else{
            input.setText("输入");
        }
    }//GEN-LAST:event_inputActionPerformed

    private void nameMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_nameMouseWheelMoved

        if(magic >= 10){
                    code.setText("#include<stdio.h>\n" +
"int main(){\n" +
"	int a;\n" +
"	scanf(\"%d\", &a);\n" +
"	printf(\"%d\", a);\n" +
"}");
        }

    }//GEN-LAST:event_nameMouseWheelMoved

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed

        int i = JOptionPane.showConfirmDialog(null, "EasyC\n作者：Lily\nE-mail：lily_easyc@sina.com\n欢迎交流！QAQ\n点击确定复制邮箱地址！");
        System.out.println(i);
        if(i == 0){
            EasyCUtilities.setClipboardText("lily_easyc@sina.com");
        }
    }//GEN-LAST:event_aboutActionPerformed

    private void codeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_codeInputMethodTextChanged

        int rowsNum = getRows()+1;
        StringBuffer sb = new StringBuffer("1");
        for(int i = 2; i <= rowsNum; i++){
            sb.append("\n"+i);
        }
        row.setText(sb.toString());
    }//GEN-LAST:event_codeInputMethodTextChanged

    private void codeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codeMouseClicked

//        PointerInfo pinfo = MouseInfo.getPointerInfo();
//        Point p = pinfo.getLocation();
//        int mx = (int) p.getX();
//        int my = (int) p.getY();
//        rightMenu.show(null, mx, my);
    }//GEN-LAST:event_codeMouseClicked

    private void copyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyMouseClicked
        System.out.println(code.getSelectedText());
        EasyCUtilities.setClipboardText(code.getSelectedText());
    }//GEN-LAST:event_copyMouseClicked

    private void pasteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasteMouseClicked
        try {
            System.out.println(EasyCUtilities.getClipboardText());
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_pasteMouseClicked

    private void openMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_openMouseWheelMoved

    }//GEN-LAST:event_openMouseWheelMoved
    public JScrollBar getLineAtCaret(JTextComponent component)
    {
//        System.out.println(codeP.getVerticalScrollBar());
        return rowP.getVerticalScrollBar();
//        int caretPosition = component.getCaretPosition();
//        Element root = component.getDocument().getDefaultRootElement();
//        return root.getElementIndex( caretPosition ) + 1;
    }
    
    private void setLineAtCaret(JScrollBar jsb) {
          codeP.setVerticalScrollBar(jsb);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EasyCFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EasyCFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EasyCFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EasyCFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EasyCFrm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about;
    private javax.swing.JTextArea code;
    private javax.swing.JScrollPane codeP;
    private javax.swing.JMenu copy;
    private javax.swing.JButton exit;
    private javax.swing.JButton input;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel name;
    private javax.swing.JButton open;
    private javax.swing.JEditorPane out;
    private javax.swing.JScrollPane outP;
    private javax.swing.JMenu paste;
    private javax.swing.JPopupMenu rightMenu;
    private javax.swing.JTextArea row;
    private javax.swing.JScrollPane rowP;
    private javax.swing.JButton run;
    private javax.swing.JButton save;
    private javax.swing.JMenu selectAll;
    // End of variables declaration//GEN-END:variables

    private int getRows() {
        return code.getText().length() - code.getText().replaceAll("\n", "").length();
    }




}
